# Generated by Django 5.0.1 on 2024-03-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('text', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
